'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("sistechy.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adicionar_item_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adicionar_item_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adicionar_item_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adicionar_item_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adicionar_item_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adicionar_item_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property agenda_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agenda_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property agenda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agenda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property agenda_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agenda_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atendimento_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atendimento_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atendimento_geral_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atendimento_geral_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atendimento_geral_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atendimento_geral_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atualizar_dados_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atualizar_dados_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atualizar_dados_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atualizar_dados_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atualizar_dados_horario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atualizar_dados_horario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atualizar_dados_horario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atualizar_dados_horario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atualizar_dados_horario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atualizar_dados_horario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atualizar_dados_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atualizar_dados_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_adicionar_item_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_adicionar_item_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_adicionar_item_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_adicionar_item_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_adicionar_item_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_adicionar_item_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_agenda_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_agenda_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_agenda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_agenda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_agenda_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_agenda_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_alterar_horario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_alterar_horario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_alterar_horario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_alterar_horario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_alterar_horario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_alterar_horario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastrar_leito_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastrar_leito_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastrar_leito_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastrar_leito_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastrar_leito_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastrar_leito_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_animal_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_animal_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_animal_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_animal_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_animal_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_animal_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_cliente_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_cliente_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_cliente_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_cliente_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_cliente_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_cliente_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_fornecedor_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_fornecedor_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_fornecedor_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_fornecedor_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_fornecedor_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_fornecedor_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_funcionario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_funcionario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_funcionario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_funcionario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cadastro_funcionario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cadastro_funcionario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_caixa_entrada_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_caixa_entrada_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_caixa_entrada_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_caixa_entrada_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_caixa_entrada_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_caixa_entrada_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cirurgia_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cirurgia_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cirurgia_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cirurgia_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_cirurgia_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_cirurgia_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_configuracoes_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_configuracoes_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_configuracoes_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_configuracoes_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_configuracoes_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_configuracoes_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_animal_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_animal_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_animal_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_animal_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_animal_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_animal_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_cliente_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_cliente_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_cliente_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_cliente_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_cliente_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_cliente_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_fornecedor_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_fornecedor_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_fornecedor_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_fornecedor_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_fornecedor_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_fornecedor_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_funcionario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_funcionario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_funcionario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_funcionario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_funcionario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_funcionario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consulta_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consulta_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consultar_item_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consultar_item_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consultar_item_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consultar_item_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consultar_item_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consultar_item_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consultar_todos_itens_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consultar_todos_itens_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consultar_todos_itens_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consultar_todos_itens_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_consultar_todos_itens_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_consultar_todos_itens_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_corpo_mensagem_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_corpo_mensagem_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_corpo_mensagem_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_corpo_mensagem_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_corpo_mensagem_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_corpo_mensagem_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_detalhes_venda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_detalhes_venda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_fundo_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_fundo_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_internacao_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_internacao_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_internacao_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_internacao_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_internacao_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_internacao_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_nova_mensagem_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_nova_mensagem_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_nova_mensagem_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_nova_mensagem_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_nova_mensagem_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_nova_mensagem_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_novo_horario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_novo_horario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_novo_horario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_novo_horario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_novo_horario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_novo_horario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_resbastecer_item_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_resbastecer_item_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_vacinacao_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_vacinacao_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_vacinacao_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_vacinacao_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_vacinacao_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_vacinacao_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_vendas_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_vendas_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastrar_novo_leito_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastrar_novo_leito_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastrar_novo_leito_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastrar_novo_leito_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastrar_novo_leito_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastrar_novo_leito_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_animal_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_animal_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_animal_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_animal_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_animal_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_animal_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_cliente_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_cliente_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_cliente_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_cliente_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_cliente_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_cliente_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_fornecedor_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_fornecedor_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_fornecedor_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_fornecedor_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_fornecedor_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_fornecedor_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_funcionario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_funcionario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_funcionario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_funcionario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_funcionario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_funcionario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_geral() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_geral", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cadastro_geral_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro_geral_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancelar_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancelar_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancelar_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartao_americanexpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartao_americanexpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartao_aura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartao_aura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartao_dinnersclub() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartao_dinnersclub", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartao_hipercard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartao_hipercard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartao_mastercard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartao_mastercard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartao_visa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartao_visa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cirurgia_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cirurgia_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cirurgia_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cirurgia_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cirurgia_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cirurgia_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configuracoes_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configuracoes_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configuracoes_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configuracoes_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configuracoes_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configuracoes_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consulta_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consulta_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consulta_geral_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consulta_geral_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consulta_geral_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consulta_geral_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_animal_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_animal_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_animal_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_animal_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_animal_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_animal_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_cliente_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_cliente_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_cliente_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_cliente_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_cliente_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_cliente_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_fornecedor_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_fornecedor_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_fornecedor_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_fornecedor_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_fornecedor_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_fornecedor_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_funcionario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_funcionario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_funcionario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_funcionario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_funcionario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_funcionario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_geral_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_geral_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_geral_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_geral_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_itens_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_itens_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_itens_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_itens_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_itens_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_itens_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_todos_itens_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_todos_itens_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_todos_itens_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_todos_itens_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_todos_itens_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_todos_itens_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultar_venda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar_venda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property detalhes_venda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("detalhes_venda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property entrada_estoque_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("entrada_estoque_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property estoque_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estoque_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property estoque_geral_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estoque_geral_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property estoque_geral_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estoque_geral_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excluir_dados_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excluir_dados_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excluir_dados_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excluir_dados_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excluir_dados_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excluir_dados_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fechar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fechar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finalizar_venda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finalizar_venda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo_splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo_splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graficos_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graficos_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graficos_geral_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graficos_geral_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internacao_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internacao_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internacao_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internacao_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internacao_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internacao_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internar_animal_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internar_animal_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internar_animal_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internar_animal_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internar_animal_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internar_animal_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoff_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoff_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marcar_novo_horario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marcar_novo_horario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marcar_novo_horario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marcar_novo_horario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marcar_novo_horario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marcar_novo_horario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nova_mensagem_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nova_mensagem_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nova_mensagem_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nova_mensagem_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nova_mensagem_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nova_mensagem_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prosseguir_venda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prosseguir_venda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reabastecer_item_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reabastecer_item_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reabastecer_item_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reabastecer_item_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reabastecer_item_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reabastecer_item_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property realizar_venda_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("realizar_venda_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property relatorios_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relatorios_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property relatorios_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relatorios_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property remover_item_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remover_item_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saida_estoque_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saida_estoque_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sair_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sair_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sair_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sair_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sair_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sair_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_alteracoes_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_alteracoes_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_alteracoes_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_alteracoes_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_alteracoes_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_alteracoes_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_cadastro_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_cadastro_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_cadastro_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_cadastro_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_cadastro_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_cadastro_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_cirurgia_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_cirurgia_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_cirurgia_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_cirurgia_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_cirurgia_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_cirurgia_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_internacao_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_internacao_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_internacao_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_internacao_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_internacao_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_internacao_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_vacinacao_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_vacinacao_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_vacinacao_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_vacinacao_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salva_vacinacao_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salva_vacinacao_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_consulta_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_consulta_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_consulta_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_consulta_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_consulta_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_consulta_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_grafico_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_grafico_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_grafico_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_grafico_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_grafico_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_grafico_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_novo_horario_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_novo_horario_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_novo_horario_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_novo_horario_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property salvar_novo_horario_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar_novo_horario_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vacinacao_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vacinacao_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vacinacao_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vacinacao_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vacinacao_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vacinacao_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property venda_geral_english_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("venda_geral_english_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property venda_geral_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("venda_geral_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property venda_geral_spanish_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("venda_geral_spanish_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
